language: c

os: linux

#Добавляем тесты
before_install:
  - sudo apt update
  - sudo apt install cppcheck
  - sudo apt install valgrind


compiler:
  - gcc
  - clang


script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cppcheck --quiet --error-exitcode=1 .
  - valgrind --leak-check=full ./*