language: c

os: linux

addons:
  apt:
    packages:
      - valgrind
      - lcov

compiler:
  - gcc
  - clang

install:
  - sudo apt-get update
  - sudo apt-get install clang-format
  - sudo apt-get install libstdc++6
  - sudo apt-get install cmake
  # Google tests
  - sudo apt-get install libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake .
  - sudo make
  - sudo cp *.a /usr/lib
  - cd -

before_script:
  - cd src
  - clang-format -i -style=Google *.h *.cpp *.c

script:
  - cmake .. #-DENABLE_STATIC_CHECK=ON
  - make
  #- ctest -VV -t memcheck


after_success:
  - lcov --capture --directory . --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info