language: c

os: linux

#Добавляем тесты
before_install:
  - sudo apt update
  - sudo apt install cppcheck
  - sudo apt install valgrind


compiler:
  - gcc
  - clang


script:
  - mkdir build
  - cd build
  - cmake .. -DENABLE_TESTS=ON
  - make