language: c

os: linux

addons:
  apt:
    packages:
      - valgrind
      - lcov
      - clang-format

before_install:
  - sudo apt update
  - cd src
  - clang-format -i -style=Google *.h *.cpp *.c

compiler:
  - gcc
  - clang


script:
  - mkdir build
  - cd build
  - cmake .. -DENABLE_TESTS=ON -DENABLE_STATIC_CHECK=ON
  - make
  - ctest -VV -t memcheck


after_success:
  - lcov --capture --directory . --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info