language: c

os: linux

addons:
  apt:
    packages:
      - valgrind

before_install:
  - sudo apt update

compiler:
  - gcc
  - clang


script:
  - mkdir build
  - cd build
  - cmake .. -DENABLE_TESTS=ON -DENABLE_STATIC_CHECK=ON
  - make
  - ctest -VV -t memcheck